# Generated by Django 4.2.13 on 2024-05-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.CharField(default='Developer', max_length=500),
        ),
    ]
